### PR TITLE
Release new everywhere

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
I think this is ready!

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@isuruf this is blocking https://github.com/conda-forge/lcalc-feedstock/pull/12 which is blocking https://github.com/conda-forge/sagelib-feedstock/pull/130

**Comment by saraedum** [comment]
@j-4 can this be merged?

**Pull request merged**
